HistoryService:
    Db:
        PostgresDataConnString:
            settings-key: HistoryService-PostgresDataConnString
        LogsConnString:
            settings-key: HistoryService-LogsConnString
            types:
                - AzureTableStorage
    Cqrs:
        RabbitConnString:
            settings-key: CqrsRabbitConnString
            types:
                - RabbitMq
    RabbitPrefetchCount:
        settings-key: HistoryService-RabbitPrefetchCount
        types:
            - Optional
    PostgresOrdersBatchSize:
        settings-key: HistoryService-PostgresOrdersBatchSize
        types:
            - Optional
    WalletIdsToLog:
        settings-key: HistoryService-WalletIdsToLog
        types: [Optional, JsonArray]
MonitoringServiceClient:
    MonitoringServiceUrl:
        settings-key: MonitoringServiceUrl
SlackNotifications:
    AzureQueue:
        ConnectionString:
            settings-key: SlackNotificationsConnString
            types:
                - AzureTableStorage
        QueueName:
            settings-key: SlackQueueName
