name: Release History client nuget

on:
  push:
    tags: "api-client-*"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    - name: Build
      run: dotnet build --configuration Release client/Antares.Service.History.GrpcClient/Antares.Service.History.GrpcClient.csproj
    - name: Create the package
      run: dotnet pack --configuration Release client/Antares.Service.History.GrpcClient /p:Version=${GITHUB_REF#refs/tags/api-client-}
    - name: Publish the package to GPR
      run: dotnet nuget push client/Antares.Service.History.GrpcClient/bin/Release/*.nupkg -s "https://api.nuget.org/v3/index.json" -k ${{ secrets.NUGET_TOCKEN }}
